# src/reports.py

from fpdf import FPDF
import os
from datetime import datetime

class SkinReport(FPDF):
    def header(self):
        # Logo or Title
        self.set_font('Arial', 'B', 15)
        self.set_text_color(255, 0, 204) # Pink
        self.cell(0, 10, 'DermAI - Personalized Skin Consultation Report', 0, 1, 'C')
        self.ln(10)

    def footer(self):
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.set_text_color(128)
        self.cell(0, 10, f'Page {self.page_no()} | Generated by DermAI AI System', 0, 0, 'C')

def generate_pdf_report(data, output_path):
    """
    Generates a professional PDF report from the prediction data.
    """
    pdf = SkinReport()
    pdf.add_page()
    
    # 1. Basic Info
    pdf.set_font('Arial', 'B', 12)
    pdf.set_text_color(0)
    pdf.cell(0, 10, f"Date: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}", 0, 1)
    pdf.cell(0, 10, f"Skin Type Profile: {data['skin_type'].capitalize()}", 0, 1)
    pdf.ln(5)

    # 2. Results Section
    pdf.set_fill_color(240, 240, 240)
    pdf.set_font('Arial', 'B', 14)
    pdf.cell(0, 10, "Detection Analysis", 1, 1, 'L', fill=True)
    
    pdf.set_font('Arial', 'B', 12)
    pdf.cell(40, 10, "Condition:", 0, 0)
    pdf.set_font('Arial', '', 12)
    pdf.cell(0, 10, data['disease'], 0, 1)
    
    pdf.set_font('Arial', 'B', 12)
    pdf.cell(40, 10, "Confidence:", 0, 0)
    pdf.set_font('Arial', '', 12)
    pdf.cell(0, 10, data['confidence'], 0, 1)
    
    pdf.set_font('Arial', 'B', 12)
    pdf.cell(40, 10, "Description:", 0, 0)
    pdf.set_font('Arial', '', 12)
    pdf.multi_cell(0, 10, data['description'])
    pdf.ln(5)

    # 3. Medicated Recommendations
    pdf.set_font('Arial', 'B', 14)
    pdf.cell(0, 10, "Clinical Recommendations", 1, 1, 'L', fill=True)
    pdf.set_font('Arial', '', 12)
    for item in data['medicated']:
        pdf.cell(0, 8, f"- {item}", 0, 1)
    pdf.ln(5)

    # 4. Herbal Recommendations
    pdf.set_font('Arial', 'B', 14)
    pdf.cell(0, 10, "Herbal & Natural Remedies", 1, 1, 'L', fill=True)
    pdf.set_font('Arial', '', 12)
    for item in data['herbal']:
        pdf.cell(0, 8, f"- {item}", 0, 1)
    pdf.ln(5)

    # 5. Lifestyle & Skin Advice
    pdf.set_font('Arial', 'B', 14)
    pdf.cell(0, 10, "Personalized Lifestyle Advice", 1, 1, 'L', fill=True)
    pdf.set_font('Arial', '', 12)
    pdf.multi_cell(0, 10, data['lifestyle'])
    pdf.ln(5)
    
    pdf.set_font('Arial', 'B', 12)
    pdf.cell(0, 10, "Skin Type Specific Notes:", 0, 1)
    pdf.set_font('Arial', '', 12)
    pdf.multi_cell(0, 10, data['skin_advice'])

    # Disclaimer
    pdf.ln(10)
    pdf.set_font('Arial', 'B', 10)
    pdf.set_text_color(200, 0, 0)
    pdf.multi_cell(0, 5, "DISCLAIMER: This report is generated by an AI system for educational purposes and should not be considered a medical diagnosis. Please consult a board-certified dermatologist for clinical assessment.")

    pdf.output(output_path)
    return output_path
